// Load environment variables (not strictly needed for this script, but good practice if it uses other env vars)
require('dotenv').config();

const admin = require('firebase-admin');

// --- Firebase Admin SDK Initialization ---
const serviceAccount = require('./firebase-service-account.json');

// Initialize Firebase Admin SDK if not already initialized
// This prevents errors if you run this script multiple times without stopping Node processes
if (!admin.apps.length) {
  admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
  });
}

const db = admin.firestore();
console.log('Firebase Admin SDK initialized for seeding.');

// --- Seed Data Definitions ---

// Frameworks Data
const frameworksData = [
  {
    id: 'iso27001',
    name: 'ISO/IEC 27001:2022',
    description: 'Information Security Management Systems - Requirements',
    type: 'ISMS',
    pdf_url: '/docs/iso27001.pdf', // Placeholder, ensure your actual PDF is in frontend/public/docs
    icon: '🛡️'
  },
  {
    id: 'iso27002',
    name: 'ISO/IEC 27002:2022',
    description: 'Information security, cybersecurity and privacy protection — Information security controls',
    type: 'ISMS',
    pdf_url: '/docs/iso27002.pdf', // Placeholder
    icon: '📜'
  },
  {
    id: 'nist_csf_2',
    name: 'NIST Cybersecurity Framework 2.0',
    description: 'A cybersecurity framework for managing and reducing cybersecurity risk.',
    type: 'ISMS',
    pdf_url: '/docs/nist_csf_2.pdf', // Placeholder
    icon: '🔍'
  },
  {
    id: 'iso27017',
    name: 'ISO/IEC 27017:2015',
    description: 'Information security controls for cloud services',
    type: 'Cloud',
    pdf_url: '/docs/iso27017.pdf', // Placeholder
    icon: '☁️'
  },
  {
    id: 'iso27018',
    name: 'ISO/IEC 27018:2019',
    description: 'Protection of PII in public clouds acting as PII processors',
    type: 'Cloud',
    pdf_url: '/docs/iso27018.pdf', // Placeholder
    icon: '🔒'
  },
  {
    id: 'csa_ccm_v4',
    name: 'CSA Cloud Controls Matrix v4.0',
    description: 'Cybersecurity framework for cloud computing, mapping to many standards.',
    type: 'Cloud',
    pdf_url: '/docs/csa_ccm_v4.pdf', // Placeholder
    icon: '📈'
  },
  {
    id: 'iso42001',
    name: 'ISO/IEC 42001:2023',
    description: 'Artificial intelligence management system',
    type: 'AI',
    pdf_url: '/docs/iso42001.pdf', // Placeholder
    icon: '🧠'
  },
  {
    id: 'nist_ai_rmf',
    name: 'NIST AI Risk Management Framework',
    description: 'Guidance for managing risks of artificial intelligence.',
    type: 'AI',
    pdf_url: '/docs/nist_ai_rmf.pdf', // Placeholder
    icon: '📊'
  },
];

// Controls Data (derived from your 'Cloud Security (ISO 27017).csv' input)
const controlsData = [
  // CLD.5.1
  {
    id: 'CLD.5.1-1',
    framework_id: 'iso27017',
    control_objective: 'Shared Security Responsibilities',
    audit_question: 'Has your organization formally documented the shared security responsibilities with your cloud provider?\n\nA) Yes, all responsibilities are defined and approved in SLAs and contracts\nB) We rely on the cloud provider’s default security measures\nC) Only critical security responsibilities are documented, others are assumed\nD) No, we have not explicitly documented security responsibilities',
    intent_explanation: 'ISO/IEC 27017 emphasizes defining and documenting shared security responsibilities between the cloud provider and the customer. This includes clarifying roles in governance, risk management, compliance, and security ownership. A well-structured SLA should outline these responsibilities, ensuring accountability and alignment with regulatory and contractual obligations.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Service Level Agreement (SLA)',
  },
  {
    id: 'CLD.5.1-2',
    framework_id: 'iso27017',
    control_objective: 'Shared Security Responsibilities',
    audit_question: 'How does your organization verify that the cloud provider fulfills their security responsibilities as per the SLA?\n\nA) By conducting regular third-party security audits and compliance checks\nB) By assuming the provider meets security obligations without verification\nC) By relying only on the provider’s compliance certificates\nD) We do not verify security responsibilities at all',
    intent_explanation: 'ISO/IEC 27017 emphasizes defining and documenting shared security responsibilities between the cloud provider and the customer. This includes clarifying roles in governance, risk management, compliance, and security ownership. A well-structured SLA should outline these responsibilities, ensuring accountability and alignment with regulatory and contractual obligations.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Shared Responsibility Matrix',
  },
  {
    id: 'CLD.5.1-3',
    framework_id: 'iso27017',
    control_objective: 'Shared Security Responsibilities',
    audit_question: 'Does your organization have a risk assessment process in place for evaluating shared security risks with your cloud provider?\n\nA) Yes, risk assessments are conducted periodically and reviewed against SLAs\nB) Risk assessments are only performed when incidents occur\nC) We trust the cloud provider’s risk management process entirely\nD) No, we do not conduct formal risk assessments',
    intent_explanation: 'ISO/IEC 27017 emphasizes defining and documenting shared security responsibilities between the cloud provider and the customer. This includes clarifying roles in governance, risk management, compliance, and security ownership. A well-structured SLA should outline these responsibilities, ensuring accountability and alignment with regulatory and contractual obligations.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Cloud Security Policy',
  },
  {
    id: 'CLD.5.1-4',
    framework_id: 'iso27017',
    control_objective: 'Shared Security Responsibilities',
    audit_question: 'In case of a security incident, how does your organization coordinate incident response activities with the cloud provider?\n\nA) We have a documented Incident Response Plan (IRP) detailing roles and escalation paths\nB) We rely on the cloud provider’s standard incident response processes\nC) We respond to incidents internally without involving the provider\nD) We do not have a structured incident response coordination process',
    intent_explanation: 'ISO/IEC 27017 emphasizes defining and documenting shared security responsibilities between the cloud provider and the customer. This includes clarifying roles in governance, risk management, compliance, and security ownership. A well-structured SLA should outline these responsibilities, ensuring accountability and alignment with regulatory and contractual obligations.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Third-Party Audit Reports',
  },
  {
    id: 'CLD.5.1-5',
    framework_id: 'iso27017',
    control_objective: 'Shared Security Responsibilities',
    audit_question: 'How does your organization track compliance with regulatory requirements (e.g., GDPR, ISO 27017) in a shared responsibility model?\n\nA) We maintain compliance documentation and verify provider adherence through audits\nB) We assume compliance since the provider is ISO-certified\nC) Compliance tracking is managed by the provider, and we do not intervene\nD) We have no formal compliance tracking mechanisms',
    intent_explanation: 'ISO/IEC 27017 emphasizes defining and documenting shared security responsibilities between the cloud provider and the customer. This includes clarifying roles in governance, risk management, compliance, and security ownership. A well-structured SLA should outline these responsibilities, ensuring accountability and alignment with regulatory and contractual obligations.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Risk Assessment Documentation',
  },
  {
    id: 'CLD.5.1-6',
    framework_id: 'iso27017',
    control_objective: 'Shared Security Responsibilities',
    audit_question: 'How is data encryption managed between your organization and the cloud provider?\n\nA) Responsibilities for encryption (at-rest, in-transit) are clearly defined in SLAs\nB) Encryption is solely managed by the cloud provider\nC) The organization encrypts data but does not verify provider-side encryption\nD) No formal encryption policies are in place',
    intent_explanation: 'ISO/IEC 27017 emphasizes defining and documenting shared security responsibilities between the cloud provider and the customer. This includes clarifying roles in governance, risk management, compliance, and security ownership. A well-structured SLA should outline these responsibilities, ensuring accountability and alignment with regulatory and contractual obligations.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Incident Response Plan (IRP)',
  },
  {
    id: 'CLD.5.1-7',
    framework_id: 'iso27017',
    control_objective: 'Shared Security Responsibilities',
    audit_question: 'Are access controls clearly defined between your organization and the cloud provider?\n\nA) Yes, access control roles and privileges are documented and enforced\nB) We rely on provider-defined default access control policies\nC) Employees share credentials for cloud service access\nD) Access control responsibilities are unclear',
    intent_explanation: 'ISO/IEC 27017 emphasizes defining and documenting shared security responsibilities between the cloud provider and the customer. This includes clarifying roles in governance, risk management, compliance, and security ownership. A well-structured SLA should outline these responsibilities, ensuring accountability and alignment with regulatory and contractual obligations.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Access Control Policies',
  },
  {
    id: 'CLD.5.1-8',
    framework_id: 'iso27017',
    control_objective: 'Shared Security Responsibilities',
    audit_question: 'How does your organization ensure that logging and monitoring responsibilities are met in the cloud environment?\n\nA) We have defined logging responsibilities and review logs regularly\nB) We rely on the provider’s logs but do not conduct reviews\nC) Logging is enabled but not actively monitored\nD) No logging and monitoring procedures are in place',
    intent_explanation: 'ISO/IEC 27017 emphasizes defining and documenting shared security responsibilities between the cloud provider and the customer. This includes clarifying roles in governance, risk management, compliance, and security ownership. A well-structured SLA should outline these responsibilities, ensuring accountability and alignment with regulatory and contractual obligations.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Compliance Documentation',
  },
  {
    id: 'CLD.5.1-9',
    framework_id: 'iso27017',
    control_objective: 'Shared Security Responsibilities',
    audit_question: 'Is there a process for reviewing and updating shared security responsibilities when adopting new cloud services or configurations?\n\nA) Yes, reviews are conducted before any new cloud service adoption\nB) We assume existing agreements apply to new services\nC) Security responsibilities are only reviewed in case of compliance audits\nD) We do not have a defined process for updating responsibilities',
    intent_explanation: 'ISO/IEC 27017 emphasizes defining and documenting shared security responsibilities between the cloud provider and the customer. This includes clarifying roles in governance, risk management, compliance, and security ownership. A well-structured SLA should outline these responsibilities, ensuring accountability and alignment with regulatory and contractual obligations.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Security Awareness Training Records',
  },
  {
    id: 'CLD.5.1-10',
    framework_id: 'iso27017',
    control_objective: 'Shared Security Responsibilities',
    audit_question: 'How does your organization ensure continuous compliance with the shared responsibility model?\n\nA) Through periodic security assessments, audits, and compliance reviews\nB) By reviewing provider certifications without additional verification\nC) By relying on provider security measures without conducting internal checks\nD) We do not monitor compliance after initial cloud adoption',
    intent_explanation: 'ISO/IEC 27017 emphasizes defining and documenting shared security responsibilities between the cloud provider and the customer. This includes clarifying roles in governance, risk management, compliance, and security ownership. A well-structured SLA should outline these responsibilities, ensuring accountability and alignment with regulatory and contractual obligations.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Provider Compliance Reports',
  },
  // CLD.5.2
  {
    id: 'CLD.5.2-1',
    framework_id: 'iso27017',
    control_objective: 'Cloud Service Agreements (CSA) & Contracts',
    audit_question: 'Has your organization formally documented a Cloud Service Agreement (CSA) with your cloud provider?\n\nA) Yes, a comprehensive CSA is in place, covering security, compliance, and legal terms\nB) We rely on the provider’s default terms without modifications\nC) Only pricing and uptime guarantees are documented, not security responsibilities\nD) No formal CSA exists between our organization and the cloud provider',
    intent_explanation: 'ISO/IEC 27017 requires organizations to establish clear and legally binding Cloud Service Agreements (CSA) and contracts that define security responsibilities, risk allocation, compliance requirements, provider obligations, confidentiality, audit rights, and data processing terms. These agreements ensure transparency and accountability, helping clients mitigate security and regulatory risks when using cloud services.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Cloud Service Agreement (CSA)',
  },
  {
    id: 'CLD.5.2-2',
    framework_id: 'iso27017',
    control_objective: 'Cloud Service Agreements (CSA) & Contracts',
    audit_question: 'Does the CSA explicitly define security responsibilities between your organization and the cloud provider?\n\nA) Yes, the agreement outlines detailed security roles and obligations\nB) It mentions security in general terms but lacks detailed responsibility definitions\nC) Security is implied, but no explicit terms are included\nD) The provider’s security responsibilities are not addressed in the agreement',
    intent_explanation: 'ISO/IEC 27017 requires organizations to establish clear and legally binding Cloud Service Agreements (CSA) and contracts that define security responsibilities, risk allocation, compliance requirements, provider obligations, confidentiality, audit rights, and data processing terms. These agreements ensure transparency and accountability, helping clients mitigate security and regulatory risks when using cloud services.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Service Level Agreement (SLA)',
  },
  {
    id: 'CLD.5.2-3',
    framework_id: 'iso27017',
    control_objective: 'Cloud Service Agreements (CSA) & Contracts',
    audit_question: 'How does your organization verify that the cloud provider meets its security obligations as per the CSA?\n\nA) Through independent security audits and compliance assessments\nB) By assuming the provider follows best practices without verification\nC) By reviewing the provider’s website for security claims\nD) We do not have a verification process for provider compliance',
    intent_explanation: 'ISO/IEC 27017 requires organizations to establish clear and legally binding Cloud Service Agreements (CSA) and contracts that define security responsibilities, risk allocation, compliance requirements, provider obligations, confidentiality, audit rights, and data processing terms. These agreements ensure transparency and accountability, helping clients mitigate security and regulatory risks when using cloud services.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Data Processing Agreement (DPA)',
  },
  {
    id: 'CLD.5.2-4',
    framework_id: 'iso27017',
    control_objective: 'Cloud Service Agreements (CSA) & Contracts',
    audit_question: 'Does the CSA include provisions for data processing and confidentiality in compliance with regulations (e.g., GDPR, ISO/IEC 27017)?\n\nA) Yes, the agreement clearly defines data processing, confidentiality, and regulatory compliance\nB) Some confidentiality clauses exist, but regulatory requirements are not explicitly covered\nC) Data confidentiality is left to the provider’s discretion\nD) The agreement does not mention data confidentiality or processing',
    intent_explanation: 'ISO/IEC 27017 requires organizations to establish clear and legally binding Cloud Service Agreements (CSA) and contracts that define security responsibilities, risk allocation, compliance requirements, provider obligations, confidentiality, audit rights, and data processing terms. These agreements ensure transparency and accountability, helping clients mitigate security and regulatory risks when using cloud services.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Audit Rights Documentation',
  },
  {
    id: 'CLD.5.2-5',
    framework_id: 'iso27017',
    control_objective: 'Cloud Service Agreements (CSA) & Contracts',
    audit_question: 'What risk allocation mechanisms are included in your CSA to manage security incidents and breaches?\n\nA) Clearly defined liability clauses, breach notification timelines, and penalties\nB) The provider is fully responsible for all security incidents\nC) There is no mention of risk allocation or liability for security breaches\nD) The organization assumes all risks without legal recourse against the provider',
    intent_explanation: 'ISO/IEC 27017 requires organizations to establish clear and legally binding Cloud Service Agreements (CSA) and contracts that define security responsibilities, risk allocation, compliance requirements, provider obligations, confidentiality, audit rights, and data processing terms. These agreements ensure transparency and accountability, helping clients mitigate security and regulatory risks when using cloud services.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Risk Allocation and Liability Clauses',
  },
  {
    id: 'CLD.5.2-6',
    framework_id: 'iso27017',
    control_objective: 'Cloud Service Agreements (CSA) & Contracts',
    audit_question: 'Does your CSA include the right to audit the cloud provider’s security and compliance measures?\n\nA) Yes, audit rights are explicitly granted, with clear audit procedures\nB) Limited audit rights are provided but require provider approval\nC) Audit rights are mentioned but not practically enforceable\nD) No audit rights are included in the agreement',
    intent_explanation: 'ISO/IEC 27017 requires organizations to establish clear and legally binding Cloud Service Agreements (CSA) and contracts that define security responsibilities, risk allocation, compliance requirements, provider obligations, confidentiality, audit rights, and data processing terms. These agreements ensure transparency and accountability, helping clients mitigate security and regulatory risks when using cloud services.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Contract Review Reports',
  },
  {
    id: 'CLD.5.2-7',
    framework_id: 'iso27017',
    control_objective: 'Cloud Service Agreements (CSA) & Contracts',
    audit_question: 'How does your organization ensure that the CSA remains aligned with evolving security and compliance requirements?\n\nA) Through periodic contract reviews and renegotiations\nB) We rely on the provider to update terms when needed\nC) We assume the CSA remains valid indefinitely without updates\nD) We do not monitor or update the CSA once signed',
    intent_explanation: 'ISO/IEC 27017 requires organizations to establish clear and legally binding Cloud Service Agreements (CSA) and contracts that define security responsibilities, risk allocation, compliance requirements, provider obligations, confidentiality, audit rights, and data processing terms. These agreements ensure transparency and accountability, helping clients mitigate security and regulatory risks when using cloud services.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Provider Compliance Certifications',
  },
  {
    id: 'CLD.5.2-8',
    framework_id: 'iso27017',
    control_objective: 'Cloud Service Agreements (CSA) & Contracts',
    audit_question: 'Are there provisions in the CSA for contract termination, ensuring secure data migration and deletion?\n\nA) Yes, the agreement includes detailed exit strategies and secure data handling requirements\nB) Termination provisions exist, but they do not address data security\nC) The agreement does not specify termination or data migration processes\nD) We have not reviewed the contract’s termination clauses',
    intent_explanation: 'ISO/IEC 27017 requires organizations to establish clear and legally binding Cloud Service Agreements (CSA) and contracts that define security responsibilities, risk allocation, compliance requirements, provider obligations, confidentiality, audit rights, and data processing terms. These agreements ensure transparency and accountability, helping clients mitigate security and regulatory risks when using cloud services.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Termination and Data Migration Policies',
  },
  {
    id: 'CLD.5.2-9',
    framework_id: 'iso27017',
    control_objective: 'Cloud Service Agreements (CSA) & Contracts',
    audit_question: 'Does the CSA include a Service Level Agreement (SLA) specifying security, uptime, and compliance commitments?\n\nA) Yes, the SLA defines clear security, availability, and compliance metrics\nB) The SLA only covers uptime and does not mention security\nC) Security commitments are loosely defined without enforceable clauses\nD) The provider does not offer an SLA for security or compliance',
    intent_explanation: 'ISO/IEC 27017 requires organizations to establish clear and legally binding Cloud Service Agreements (CSA) and contracts that define security responsibilities, risk allocation, compliance requirements, provider obligations, confidentiality, audit rights, and data processing terms. These agreements ensure transparency and accountability, helping clients mitigate security and regulatory risks when using cloud services.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Incident Response and Breach Notification Clauses',
  },
  {
    id: 'CLD.5.2-10',
    framework_id: 'iso27017',
    control_objective: 'Cloud Service Agreements (CSA) & Contracts',
    audit_question: 'How does your organization handle disputes regarding security obligations in the CSA?\n\nA) Through predefined dispute resolution mechanisms within the contract\nB) By negotiating with the provider informally when disputes arise\nC) We rely on legal action as the first response to disputes\nD) There is no formal dispute resolution process in place',
    intent_explanation: 'ISO/IEC 27017 requires organizations to establish clear and legally binding Cloud Service Agreements (CSA) and contracts that define security responsibilities, risk allocation, compliance requirements, provider obligations, confidentiality, audit rights, and data processing terms. These agreements ensure transparency and accountability, helping clients mitigate security and regulatory risks when using cloud services.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Dispute Resolution Procedures',
  },
  // CLD.5.3
  {
    id: 'CLD.5.3-1',
    framework_id: 'iso27017',
    control_objective: 'Cloud Compliance & Regulatory Adherence',
    audit_question: 'How does your organization determine which compliance frameworks (e.g., GDPR, HIPAA, PCI DSS) apply to your cloud environment?\n\nA) Through a formal compliance risk assessment and regulatory mapping\nB) We rely on the cloud provider’s compliance claims without verification\nC) We assume our on-premise compliance policies automatically apply to the cloud\nD) We do not conduct formal compliance assessments for cloud services',
    intent_explanation: 'ISO/IEC 27017 requires organizations to ensure that cloud services comply with applicable regulatory and industry standards, such as GDPR, HIPAA, PCI DSS, FedRAMP, NIST, and CSA STAR. Compliance efforts should include regular risk assessments, audits, and governance frameworks to manage cloud-related security and legal obligations effectively.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Regulatory Compliance Assessment Reports',
  },
  {
    id: 'CLD.5.3-2',
    framework_id: 'iso27017',
    control_objective: 'Cloud Compliance & Regulatory Adherence',
    audit_question: 'Does your organization regularly conduct compliance audits of its cloud service usage?\n\nA) Yes, internal and third-party audits are performed at scheduled intervals\nB) Audits are conducted only when required by external regulators\nC) We rely solely on the cloud provider’s compliance certifications\nD) No, we do not perform specific cloud compliance audits',
    intent_explanation: 'ISO/IEC 27017 requires organizations to ensure that cloud services comply with applicable regulatory and industry standards, such as GDPR, HIPAA, PCI DSS, FedRAMP, NIST, and CSA STAR. Compliance efforts should include regular risk assessments, audits, and governance frameworks to manage cloud-related security and legal obligations effectively.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Compliance Audit Reports',
  },
  {
    id: 'CLD.5.3-3',
    framework_id: 'iso27017',
    control_objective: 'Cloud Compliance & Regulatory Adherence',
    audit_question: 'How does your organization verify that cloud providers comply with ISO/IEC 27017 and other applicable standards?\n\nA) By reviewing the provider’s certifications and conducting independent audits\nB) By assuming certification ensures full compliance without further checks\nC) By relying on provider documentation without validation\nD) We do not verify cloud provider compliance with security standards',
    intent_explanation: 'ISO/IEC 27017 requires organizations to ensure that cloud services comply with applicable regulatory and industry standards, such as GDPR, HIPAA, PCI DSS, FedRAMP, NIST, and CSA STAR. Compliance efforts should include regular risk assessments, audits, and governance frameworks to manage cloud-related security and legal obligations effectively.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Cloud Provider Compliance Certifications',
  },
  {
    id: 'CLD.5.3-4',
    framework_id: 'iso27017',
    control_objective: 'Cloud Compliance & Regulatory Adherence',
    audit_question: 'Does your organization maintain documented evidence of cloud compliance for regulatory audits?\n\nA) Yes, compliance documentation is maintained and updated regularly\nB) Some documentation exists but is not consistently updated\nC) We rely on verbal confirmations from the cloud provider\nD) No formal compliance documentation is maintained',
    intent_explanation: 'ISO/IEC 27017 requires organizations to ensure that cloud services comply with applicable regulatory and industry standards, such as GDPR, HIPAA, PCI DSS, FedRAMP, NIST, and CSA STAR. Compliance efforts should include regular risk assessments, audits, and governance frameworks to manage cloud-related security and legal obligations effectively.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Data Processing Agreement (DPA)',
  },
  {
    id: 'CLD.5.3-5',
    framework_id: 'iso27017',
    control_objective: 'Cloud Compliance & Regulatory Adherence',
    audit_question: 'How does your organization ensure that cloud data processing meets GDPR or other data protection laws?\n\nA) By enforcing a Data Processing Agreement (DPA) and conducting periodic compliance reviews\nB) We assume that the cloud provider is automatically GDPR compliant\nC) We follow GDPR only for on-premise systems, not the cloud\nD) We do not actively ensure cloud compliance with GDPR',
    intent_explanation: 'ISO/IEC 27017 requires organizations to ensure that cloud services comply with applicable regulatory and industry standards, such as GDPR, HIPAA, PCI DSS, FedRAMP, NIST, and CSA STAR. Compliance efforts should include regular risk assessments, audits, and governance frameworks to manage cloud-related security and legal obligations effectively.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Contractual Compliance Clauses',
  },
  {
    id: 'CLD.5.3-6',
    framework_id: 'iso27017',
    control_objective: 'Cloud Compliance & Regulatory Adherence',
    audit_question: 'Are third-party security and compliance assessments performed on your cloud provider?\n\nA) Yes, we conduct or commission independent audits for verification\nB) We rely on provider-issued compliance reports without external validation\nC) Assessments are done only when compliance issues arise\nD) No, we do not assess provider compliance externally',
    intent_explanation: 'ISO/IEC 27017 requires organizations to ensure that cloud services comply with applicable regulatory and industry standards, such as GDPR, HIPAA, PCI DSS, FedRAMP, NIST, and CSA STAR. Compliance efforts should include regular risk assessments, audits, and governance frameworks to manage cloud-related security and legal obligations effectively.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Risk Assessment and Mitigation Plans',
  },
  {
    id: 'CLD.5.3-7',
    framework_id: 'iso27017',
    control_objective: 'Cloud Compliance & Regulatory Adherence',
    audit_question: 'How does your organization handle compliance gaps identified in cloud security audits?\n\nA) By implementing corrective actions and tracking remediation progress\nB) By accepting minor compliance gaps if they don’t impact core operations\nC) By deferring the responsibility to the cloud provider\nD) We do not have a defined process for addressing compliance gaps',
    intent_explanation: 'ISO/IEC 27017 requires organizations to ensure that cloud services comply with applicable regulatory and industry standards, such as GDPR, HIPAA, PCI DSS, FedRAMP, NIST, and CSA STAR. Compliance efforts should include regular risk assessments, audits, and governance frameworks to manage cloud-related security and legal obligations effectively.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Compliance Monitoring Program Documentation',
  },
  {
    id: 'CLD.5.3-8',
    framework_id: 'iso27017',
    control_objective: 'Cloud Compliance & Regulatory Adherence',
    audit_question: 'Does your organization ensure that cloud contracts include compliance obligations (e.g., PCI DSS for payment data, HIPAA for healthcare data)?\n\nA) Yes, compliance obligations are explicitly documented in contracts\nB) Compliance is implied but not contractually enforced\nC) The provider’s general compliance is assumed to cover all obligations\nD) Contracts do not reference specific compliance requirements',
    intent_explanation: 'ISO/IEC 27017 requires organizations to ensure that cloud services comply with applicable regulatory and industry standards, such as GDPR, HIPAA, PCI DSS, FedRAMP, NIST, and CSA STAR. Compliance efforts should include regular risk assessments, audits, and governance frameworks to manage cloud-related security and legal obligations effectively.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Incident and Breach Handling Policies',
  },
  {
    id: 'CLD.5.3-9',
    framework_id: 'iso27017',
    control_objective: 'Cloud Compliance & Regulatory Adherence',
    audit_question: 'How does your organization track updates to cloud-related regulatory requirements?\n\nA) Through a compliance monitoring program and regulatory updates tracking\nB) We review compliance only when auditors request updates\nC) We rely on the cloud provider to notify us of changes\nD) We do not actively track changes in compliance requirements',
    intent_explanation: 'ISO/IEC 27017 requires organizations to ensure that cloud services comply with applicable regulatory and industry standards, such as GDPR, HIPAA, PCI DSS, FedRAMP, NIST, and CSA STAR. Compliance efforts should include regular risk assessments, audits, and governance frameworks to manage cloud-related security and legal obligations effectively.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Third-Party Security Assessment Reports',
  },
  {
    id: 'CLD.5.3-10',
    framework_id: 'iso27017',
    control_objective: 'Cloud Compliance & Regulatory Adherence',
    audit_question: 'How does your organization ensure encryption and data protection controls comply with applicable regulations?\n\nA) By aligning encryption policies with compliance standards and verifying implementation\nB) By assuming provider-side encryption is sufficient without verification\nC) We encrypt data but do not validate compliance with regulations\nD) We do not enforce encryption compliance in cloud environments',
    intent_explanation: 'ISO/IEC 27017 requires organizations to ensure that cloud services comply with applicable regulatory and industry standards, such as GDPR, HIPAA, PCI DSS, FedRAMP, NIST, and CSA STAR. Compliance efforts should include regular risk assessments, audits, and governance frameworks to manage cloud-related security and legal obligations effectively.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Encryption & Data Security Policies',
  },
  // CLD.5.4
  {
    id: 'CLD.5.4-1',
    framework_id: 'iso27017',
    control_objective: 'Cloud Security Awareness & Training',
    audit_question: 'Does your organization have a formal cloud security training program for employees?\n\nA) Yes, all employees receive regular cloud security training\nB) Training is provided only to IT and security teams\nC) Employees are expected to self-learn cloud security best practices\nD) No formal cloud security training program exists',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement comprehensive cloud security awareness and training programs to mitigate insider threats, phishing risks, and misconfigurations. Employees must undergo continuous learning on secure cloud practices, compliance, and threat response, with certifications like CCSP, AWS Security, and CompTIA Cloud+ encouraged for key personnel.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Cloud Security Training Policy',
  },
  {
    id: 'CLD.5.4-2',
    framework_id: 'iso27017',
    control_objective: 'Cloud Security Awareness & Training',
    audit_question: 'How often does your organization conduct cloud security awareness training?\n\nA) At least annually, with periodic refresher courses\nB) Only during employee onboarding\nC) Only after a security incident has occurred\nD) No structured training schedule exists',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement comprehensive cloud security awareness and training programs to mitigate insider threats, phishing risks, and misconfigurations. Employees must undergo continuous learning on secure cloud practices, compliance, and threat response, with certifications like CCSP, AWS Security, and CompTIA Cloud+ encouraged for key personnel.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Training Attendance Records',
  },
  {
    id: 'CLD.5.4-3',
    framework_id: 'iso27017',
    control_objective: 'Cloud Security Awareness & Training',
    audit_question: 'Does cloud security training cover insider threats and employee responsibilities?\n\nA) Yes, insider threat prevention and role-based security responsibilities are included\nB) Training is focused only on external threats, not internal risks\nC) Security awareness is left to individual employees\nD) We do not address insider threats in our training',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement comprehensive cloud security awareness and training programs to mitigate insider threats, phishing risks, and misconfigurations. Employees must undergo continuous learning on secure cloud practices, compliance, and threat response, with certifications like CCSP, AWS Security, and CompTIA Cloud+ encouraged for key personnel.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Phishing Simulation Reports',
  },
  {
    id: 'CLD.5.4-4',
    framework_id: 'iso27017',
    control_objective: 'Cloud Security Awareness & Training',
    audit_question: 'How does your organization assess the effectiveness of cloud security training?\n\nA) Through post-training assessments, phishing simulations, and incident analysis\nB) By tracking attendance but not testing knowledge retention\nC) We assume employees understand security after attending sessions\nD) No formal assessment methods are used',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement comprehensive cloud security awareness and training programs to mitigate insider threats, phishing risks, and misconfigurations. Employees must undergo continuous learning on secure cloud practices, compliance, and threat response, with certifications like CCSP, AWS Security, and CompTIA Cloud+ encouraged for key personnel.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Training Modules & Content',
  },
  {
    id: 'CLD.5.4-5',
    framework_id: 'iso27017',
    control_objective: 'Cloud Security Awareness & Training',
    audit_question: 'Does your cloud security training include phishing prevention techniques?\n\nA) Yes, employees receive phishing awareness training and simulated attack tests\nB) Phishing awareness is mentioned but not actively tested\nC) Only IT staff are trained on phishing threats\nD) We do not provide phishing training to employees',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement comprehensive cloud security awareness and training programs to mitigate insider threats, phishing risks, and misconfigurations. Employees must undergo continuous learning on secure cloud practices, compliance, and threat response, with certifications like CCSP, AWS Security, and CompTIA Cloud+ encouraged for key personnel.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Security Certification Records',
  },
  {
    id: 'CLD.5.4-6',
    framework_id: 'iso27017',
    control_objective: 'Cloud Security Awareness & Training',
    audit_question: 'Do employees handling cloud services receive specialized security certifications (e.g., CCSP, AWS Security, CompTIA Cloud+)?\n\nA) Yes, employees are encouraged or required to obtain relevant certifications\nB) Some employees pursue certifications on their own, but it’s not mandated\nC) We rely on provider documentation instead of certifications\nD) No certification programs are in place',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement comprehensive cloud security awareness and training programs to mitigate insider threats, phishing risks, and misconfigurations. Employees must undergo continuous learning on secure cloud practices, compliance, and threat response, with certifications like CCSP, AWS Security, and CompTIA Cloud+ encouraged for key personnel.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Training Effectiveness Assessments',
  },
  {
    id: 'CLD.5.4-7',
    framework_id: 'iso27017',
    control_objective: 'Cloud Security Awareness & Training',
    audit_question: 'Does your organization provide role-specific cloud security training?\n\nA) Yes, different teams (IT, DevOps, HR, etc.) receive tailored training\nB) A general cloud security course is provided for all employees\nC) Only IT personnel receive cloud security training\nD) No role-specific training exists',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement comprehensive cloud security awareness and training programs to mitigate insider threats, phishing risks, and misconfigurations. Employees must undergo continuous learning on secure cloud practices, compliance, and threat response, with certifications like CCSP, AWS Security, and CompTIA Cloud+ encouraged for key personnel.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Policy Acknowledgment Records',
  },
  {
    id: 'CLD.5.4-8',
    framework_id: 'iso27017',
    control_objective: 'Cloud Security Awareness & Training',
    audit_question: 'How does your organization ensure continuous learning in cloud security?\n\nA) Through regular training, webinars, and certification incentives\nB) Employees receive a one-time training session but no ongoing education\nC) Employees are expected to self-educate without structured programs\nD) We do not focus on continuous learning for cloud security',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement comprehensive cloud security awareness and training programs to mitigate insider threats, phishing risks, and misconfigurations. Employees must undergo continuous learning on secure cloud practices, compliance, and threat response, with certifications like CCSP, AWS Security, and CompTIA Cloud+ encouraged for key personnel.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Continuous Learning Initiatives',
  },
  {
    id: 'CLD.5.4-9',
    framework_id: 'iso27017',
    control_objective: 'Cloud Security Awareness & Training',
    audit_question: 'Are employees trained on security misconfigurations in cloud environments?\n\nA) Yes, training includes best practices for secure cloud configurations\nB) Only IT administrators are trained on cloud misconfigurations\nC) We rely on the cloud provider to prevent misconfigurations\nD) No specific training on misconfigurations is provided',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement comprehensive cloud security awareness and training programs to mitigate insider threats, phishing risks, and misconfigurations. Employees must undergo continuous learning on secure cloud practices, compliance, and threat response, with certifications like CCSP, AWS Security, and CompTIA Cloud+ encouraged for key personnel.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Audit Trail for Training Compliance',
  },
  // CLD.6.1
  {
    id: 'CLD.6.1-1',
    framework_id: 'iso27017',
    control_objective: 'Cloud Identity and Access Management (IAM)',
    audit_question: 'How does your organization enforce authentication for cloud access?\n\nA) MFA is mandatory for all users accessing cloud resources\nB) Password-based authentication is used without MFA\nC) Employees choose their authentication methods independently\nD) No authentication policies are explicitly enforced',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement robust Identity and Access Management (IAM) policies, ensuring authentication, authorization, and least privilege principles are enforced. IAM should incorporate Multi-Factor Authentication (MFA), Role-Based Access Control (RBAC), Zero Trust security models, API access security, and identity federation to safeguard cloud environments against unauthorized access and privilege escalation.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'IAM Policy Documentation: Formal policies defining authentication, RBAC, MFA, Zero Trust, and API security controls.',
  },
  {
    id: 'CLD.6.1-2',
    framework_id: 'iso27017',
    control_objective: 'Cloud Identity and Access Management (IAM)',
    audit_question: 'How is Role-Based Access Control (RBAC) implemented in your cloud environment?\n\nA) Access is assigned based on roles, with the principle of least privilege applied\nB) Access is granted on an ad-hoc basis without predefined roles\nC) Users have full access by default unless restrictions are applied\nD) RBAC is not implemented in our cloud infrastructure',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement robust Identity and Access Management (IAM) policies, ensuring authentication, authorization, and least privilege principles are enforced. IAM should incorporate Multi-Factor Authentication (MFA), Role-Based Access Control (RBAC), Zero Trust security models, API access security, and identity federation to safeguard cloud environments against unauthorized access and privilege escalation.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Access Control Lists (ACLs): Documentation proving least privilege access enforcement in cloud environments.',
  },
  {
    id: 'CLD.6.1-3',
    framework_id: 'iso27017',
    control_objective: 'Cloud Identity and Access Management (IAM)',
    audit_question: 'How often does your organization review user access permissions to cloud resources?\n\nA) Periodic reviews are conducted at least quarterly\nB) Access reviews happen only when employees leave the organization\nC) Access permissions are granted permanently without reviews\nD) No formal access review process exists',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement robust Identity and Access Management (IAM) policies, ensuring authentication, authorization, and least privilege principles are enforced. IAM should incorporate Multi-Factor Authentication (MFA), Role-Based Access Control (RBAC), Zero Trust security models, API access security, and identity federation to safeguard cloud environments against unauthorized access and privilege escalation.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'MFA Enforcement Logs: Evidence showing MFA is enabled and required for cloud services.',
  },
  {
    id: 'CLD.6.1-4',
    framework_id: 'iso27017',
    control_objective: 'Cloud Identity and Access Management (IAM)',
    audit_question: 'Does your organization implement a Zero Trust approach to cloud security?\n\nA) Yes, all access is continuously verified regardless of user location\nB) Users within the corporate network are trusted by default\nC) Access control is only enforced for external connections\nD) Zero Trust principles are not applied to cloud security',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement robust Identity and Access Management (IAM) policies, ensuring authentication, authorization, and least privilege principles are enforced. IAM should incorporate Multi-Factor Authentication (MFA), Role-Based Access Control (RBAC), Zero Trust security models, API access security, and identity federation to safeguard cloud environments against unauthorized access and privilege escalation.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'User Access Review Reports: Periodic reports demonstrating IAM access audits and privilege reviews.',
  },
  {
    id: 'CLD.6.1-5',
    framework_id: 'iso27017',
    control_objective: 'Cloud Identity and Access Management (IAM)',
    audit_question: 'How are privileged accounts managed in your cloud environment?\n\nA) Privileged accounts have just-in-time access with strict logging and monitoring\nB) Privileged accounts are created for long-term use without monitoring\nC) Any user can request and gain admin-level access without restrictions\nD) Privileged accounts are not managed separately from regular accounts',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement robust Identity and Access Management (IAM) policies, ensuring authentication, authorization, and least privilege principles are enforced. IAM should incorporate Multi-Factor Authentication (MFA), Role-Based Access Control (RBAC), Zero Trust security models, API access security, and identity federation to safeguard cloud environments against unauthorized access and privilege escalation.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Privileged Access Management (PAM) Logs: Records tracking admin and privileged account usage.',
  },
  {
    id: 'CLD.6.1-6',
    framework_id: 'iso27017',
    control_objective: 'Cloud Identity and Access Management (IAM)',
    audit_question: 'How does your organization secure API access in cloud services?\n\nA) API access is controlled using authentication, authorization, and monitoring\nB) APIs are publicly accessible without security restrictions\nC) API security is not specifically enforced\nD) We assume the cloud provider secures APIs by default',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement robust Identity and Access Management (IAM) policies, ensuring authentication, authorization, and least privilege principles are enforced. IAM should incorporate Multi-Factor Authentication (MFA), Role-Based Access Control (RBAC), Zero Trust security models, API access security, and identity federation to safeguard cloud environments against unauthorized access and privilege escalation.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Federation Configuration Records: Proof of SAML, OAuth, or OpenID-based identity federation implementation.',
  },
  {
    id: 'CLD.6.1-7',
    framework_id: 'iso27017',
    control_objective: 'Cloud Identity and Access Management (IAM)',
    audit_question: 'What method does your organization use for federated identity management in cloud services?\n\nA) Identity Federation via SAML, OAuth, or OpenID Connect\nB) Separate user accounts are manually created for each cloud service\nC) Cloud applications use standalone authentication with no federation\nD) We do not use federated identity management',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement robust Identity and Access Management (IAM) policies, ensuring authentication, authorization, and least privilege principles are enforced. IAM should incorporate Multi-Factor Authentication (MFA), Role-Based Access Control (RBAC), Zero Trust security models, API access security, and identity federation to safeguard cloud environments against unauthorized access and privilege escalation.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'API Security Controls Evidence: API gateway logs showing authentication, encryption, and role-based API access enforcement.',
  },
  {
    id: 'CLD.6.1-8',
    framework_id: 'iso27017',
    control_objective: 'Cloud Identity and Access Management (IAM)',
    audit_question: 'How does your organization detect and respond to unauthorized access attempts?\n\nA) IAM logs and anomaly detection tools alert security teams in real time\nB) Unauthorized access is detected only during manual audits\nC) Users are trusted to report unauthorized access themselves\nD) No monitoring for unauthorized access is in place',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement robust Identity and Access Management (IAM) policies, ensuring authentication, authorization, and least privilege principles are enforced. IAM should incorporate Multi-Factor Authentication (MFA), Role-Based Access Control (RBAC), Zero Trust security models, API access security, and identity federation to safeguard cloud environments against unauthorized access and privilege escalation.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'IAM Log Monitoring Reports: Security audit logs and SIEM alerts related to access management.',
  },
  {
    id: 'CLD.6.1-9',
    framework_id: 'iso27017',
    control_objective: 'Cloud Identity and Access Management (IAM)',
    audit_question: 'Are IAM policies and controls regularly tested for vulnerabilities?\n\nA) Yes, IAM configurations undergo regular audits and penetration testing\nB) IAM security is only reviewed after security incidents occur\nC) IAM settings are configured once and not reassessed\nD) No formal IAM security testing is conducted',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement robust Identity and Access Management (IAM) policies, ensuring authentication, authorization, and least privilege principles are enforced. IAM should incorporate Multi-Factor Authentication (MFA), Role-Based Access Control (RBAC), Zero Trust security models, API access security, and identity federation to safeguard cloud environments against unauthorized access and privilege escalation.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Incident Response Records: Documentation of actions taken on unauthorized access attempts.',
  },
  {
    id: 'CLD.6.1-10',
    framework_id: 'iso27017',
    control_objective: 'Cloud Identity and Access Management (IAM)',
    audit_question: 'How are IAM logs managed for security auditing?\n\nA) IAM logs are collected, monitored, and retained per compliance standards\nB) IAM logs are stored but not actively reviewed\nC) IAM logs are deleted after a short retention period\nD) IAM logging is not enabled for cloud access events',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement robust Identity and Access Management (IAM) policies, ensuring authentication, authorization, and least privilege principles are enforced. IAM should incorporate Multi-Factor Authentication (MFA), Role-Based Access Control (RBAC), Zero Trust security models, API access security, and identity federation to safeguard cloud environments against unauthorized access and privilege escalation.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Penetration Testing & Audit Reports: Results of security tests evaluating IAM configurations.',
  },
  // CLD.6.2
  {
    id: 'CLD.6.2-1',
    framework_id: 'iso27017',
    control_objective: 'Privileged Access Management (PAM)',
    audit_question: 'How does your organization enforce privileged access controls for cloud administrators?\n\nA) PAM solutions are used to manage and monitor privileged access\nB) Administrators use shared credentials without tracking\nC) Privileged users have permanent admin access without restrictions\nD) No specific privileged access controls are in place',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement Privileged Access Management (PAM) to secure administrator accounts, enforce just-in-time (JIT) access, and prevent privilege escalation in cloud environments. PAM controls must ensure multi-factor authentication (MFA), session monitoring, strict access reviews, and least privilege principles to protect critical cloud infrastructure.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Privileged Access Policy: Documented policies outlining PAM implementation, JIT access, and privilege escalation controls.',
  },
  {
    id: 'CLD.6.2-2',
    framework_id: 'iso27017',
    control_objective: 'Privileged Access Management (PAM)',
    audit_question: 'Does your organization implement Just-In-Time (JIT) access for privileged users?\n\nA) Yes, admin accounts are provisioned only when needed and revoked after use\nB) Privileged users always have full-time access\nC) JIT access is considered but not implemented\nD) There are no time-based restrictions on privileged accounts',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement Privileged Access Management (PAM) to secure administrator accounts, enforce just-in-time (JIT) access, and prevent privilege escalation in cloud environments. PAM controls must ensure multi-factor authentication (MFA), session monitoring, strict access reviews, and least privilege principles to protect critical cloud infrastructure.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'PAM Solution Configuration: Evidence of privileged access enforcement via automated tools (e.g., CyberArk, BeyondTrust, AWS IAM).',
  },
  {
    id: 'CLD.6.2-3',
    framework_id: 'iso27017',
    control_objective: 'Privileged Access Management (PAM)',
    audit_question: 'How are privileged user activities monitored in your cloud environment?\n\nA) All privileged sessions are logged and reviewed periodically\nB) Privileged access is granted without monitoring\nC) Logs are only reviewed after a security incident occurs\nD) There is no formal monitoring of privileged activities',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement Privileged Access Management (PAM) to secure administrator accounts, enforce just-in-time (JIT) access, and prevent privilege escalation in cloud environments. PAM controls must ensure multi-factor authentication (MFA), session monitoring, strict access reviews, and least privilege principles to protect critical cloud infrastructure.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'MFA Enforcement Logs: Logs verifying MFA is enabled for all privileged accounts.',
  },
  {
    id: 'CLD.6.2-4',
    framework_id: 'iso27017',
    control_objective: 'Privileged Access Management (PAM)',
    audit_question: 'Does your organization enforce Multi-Factor Authentication (MFA) for privileged accounts?\n\nA) Yes, MFA is mandatory for all privileged users\nB) MFA is optional for privileged accounts\nC) Only password-based authentication is used for privileged access\nD) MFA is not enforced for privileged accounts',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement Privileged Access Management (PAM) to secure administrator accounts, enforce just-in-time (JIT) access, and prevent privilege escalation in cloud environments. PAM controls must ensure multi-factor authentication (MFA), session monitoring, strict access reviews, and least privilege principles to protect critical cloud infrastructure.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Privileged User Access Review Reports: Reports showing quarterly reviews and de-provisioning of unnecessary privileged accounts.',
  },
  {
    id: 'CLD.6.2-5',
    framework_id: 'iso27017',
    control_objective: 'Privileged Access Management (PAM)',
    audit_question: 'How often are privileged access permissions reviewed?\n\nA) At least quarterly, with immediate revocation of unnecessary privileges\nB) Only when an employee leaves the organization\nC) Privileges are granted permanently without review\nD) There is no formal privileged access review process',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement Privileged Access Management (PAM) to secure administrator accounts, enforce just-in-time (JIT) access, and prevent privilege escalation in cloud environments. PAM controls must ensure multi-factor authentication (MFA), session monitoring, strict access reviews, and least privilege principles to protect critical cloud infrastructure.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Privileged Session Logging & Monitoring Reports: Records proving privileged activity is logged, monitored, and analyzed.',
  },
  {
    id: 'CLD.6.2-6',
    framework_id: 'iso27017',
    control_objective: 'Privileged Access Management (PAM)',
    audit_question: 'How does your organization prevent privilege escalation in cloud environments?\n\nA) PAM tools enforce least privilege and detect unauthorized elevation attempts\nB) Users can escalate privileges as needed without restrictions\nC) Privilege escalation is not actively monitored\nD) There is no control in place to prevent privilege escalation',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement Privileged Access Management (PAM) to secure administrator accounts, enforce just-in-time (JIT) access, and prevent privilege escalation in cloud environments. PAM controls must ensure multi-factor authentication (MFA), session monitoring, strict access reviews, and least privilege principles to protect critical cloud infrastructure.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Just-In-Time (JIT) Access Logs: Proof that privileged accounts are activated only when needed and revoked after use.',
  },
  {
    id: 'CLD.6.2-7',
    framework_id: 'iso27017',
    control_objective: 'Privileged Access Management (PAM)',
    audit_question: 'Are privileged accounts isolated from standard user accounts?\n\nA) Yes, privileged accounts are separate and not used for regular tasks\nB) Admin users use the same account for both privileged and non-privileged tasks\nC) Privileged access is shared among multiple users\nD) No distinction exists between privileged and standard accounts',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement Privileged Access Management (PAM) to secure administrator accounts, enforce just-in-time (JIT) access, and prevent privilege escalation in cloud environments. PAM controls must ensure multi-factor authentication (MFA), session monitoring, strict access reviews, and least privilege principles to protect critical cloud infrastructure.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Privilege Escalation Prevention Controls: Logs showing attempted privilege escalations and automated blocking responses.',
  },
  {
    id: 'CLD.6.2-8',
    framework_id: 'iso27017',
    control_objective: 'Privileged Access Management (PAM)',
    audit_question: 'How does your organization handle emergency access to privileged accounts?\n\nA) Emergency access is controlled through break-glass accounts with strict logging\nB) Any user can request and obtain privileged access without restrictions\nC) Privileged credentials are stored in shared locations for emergency use\nD) There is no formal policy for emergency privileged access',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement Privileged Access Management (PAM) to secure administrator accounts, enforce just-in-time (JIT) access, and prevent privilege escalation in cloud environments. PAM controls must ensure multi-factor authentication (MFA), session monitoring, strict access reviews, and least privilege principles to protect critical cloud infrastructure.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Break-Glass Account Control Records: Documentation of emergency access procedures, approvals, and logs.',
  },
  {
    id: 'CLD.6.2-9',
    framework_id: 'iso27017',
    control_objective: 'Privileged Access Management (PAM)',
    audit_question: 'Does your organization use automated tools to enforce privileged access policies?\n\nA) Yes, PAM solutions enforce access policies and monitor activity\nB) Privileged access is manually granted without automation\nC) Users manage their own privileged access without oversight\nD) No automated privileged access controls are in place',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement Privileged Access Management (PAM) to secure administrator accounts, enforce just-in-time (JIT) access, and prevent privilege escalation in cloud environments. PAM controls must ensure multi-factor authentication (MFA), session monitoring, strict access reviews, and least privilege principles to protect critical cloud infrastructure.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Privileged Access Role Separation Evidence: Proof that admin accounts are not used for daily non-administrative tasks.',
  },
  {
    id: 'CLD.6.2-10',
    framework_id: 'iso27017',
    control_objective: 'Privileged Access Management (PAM)',
    audit_question: 'Are privileged access logs integrated with a Security Information and Event Management (SIEM) system?\n\nA) Yes, privileged activity logs are collected and analyzed in SIEM\nB) Logs are stored but not actively reviewed\nC) Privileged access events are not logged\nD) No logging or SIEM integration exists for privileged accounts',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement Privileged Access Management (PAM) to secure administrator accounts, enforce just-in-time (JIT) access, and prevent privilege escalation in cloud environments. PAM controls must ensure multi-factor authentication (MFA), session monitoring, strict access reviews, and least privilege principles to protect critical cloud infrastructure.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'SIEM Integration Reports: Evidence showing privileged access logs are analyzed in a SIEM system for real-time monitoring.',
  },
  // CLD.6.3
  {
    id: 'CLD.6.3-1',
    framework_id: 'iso27017',
    control_objective: 'Identity Federation & Single Sign-On (SSO)',
    audit_question: 'Does your organization use Single Sign-On (SSO) for cloud-based applications?\n\nA) Yes, SSO is integrated with cloud identity providers\nB) Some applications support SSO, while others require separate logins\nC) Each cloud application has its own independent authentication system\nD) SSO is not implemented',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement Identity Federation and Single Sign-On (SSO) to enable centralized authentication across cloud services. This ensures secure access management by integrating trusted Cloud Identity Providers (IdPs) using protocols like OAuth, SAML, and OpenID Connect. Proper controls prevent unauthorized access and improve authentication efficiency.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'SSO Implementation Documentation: Proof of SSO integration with cloud applications using federated authentication.',
  },
  {
    id: 'CLD.6.3-2',
    framework_id: 'iso27017',
    control_objective: 'Identity Federation & Single Sign-On (SSO)',
    audit_question: 'How does your organization ensure the security of SSO authentication mechanisms?\n\nA) SSO authentication is protected with MFA and strict access controls\nB) SSO authentication relies solely on username and password\nC) Users can bypass SSO and log in with separate credentials\nD) There are no specific security controls for SSO',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement Identity Federation and Single Sign-On (SSO) to enable centralized authentication across cloud services. This ensures secure access management by integrating trusted Cloud Identity Providers (IdPs) using protocols like OAuth, SAML, and OpenID Connect. Proper controls prevent unauthorized access and improve authentication efficiency.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Federated Identity Provider (IdP) Configuration: Evidence of SAML, OAuth, or OpenID Connect integration.',
  },
  {
    id: 'CLD.6.3-3',
    framework_id: 'iso27017',
    control_objective: 'Identity Federation & Single Sign-On (SSO)',
    audit_question: 'Which protocol does your organization use for federated authentication?\n\nA) SAML, OAuth, or OpenID Connect\nB) Custom-built authentication without standard protocols\nC) Plain text credentials stored in the cloud provider’s database\nD) No federated authentication is used',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement Identity Federation and Single Sign-On (SSO) to enable centralized authentication across cloud services. This ensures secure access management by integrating trusted Cloud Identity Providers (IdPs) using protocols like OAuth, SAML, and OpenID Connect. Proper controls prevent unauthorized access and improve authentication efficiency.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'MFA Enforcement Logs: Proof that MFA is required for all federated users.',
  },
  {
    id: 'CLD.6.3-4',
    framework_id: 'iso27017',
    control_objective: 'Identity Federation & Single Sign-On (SSO)',
    audit_question: 'How does your organization handle access revocation for federated identities?\n\nA) Access is revoked at the identity provider (IdP) level, preventing further logins\nB) Cloud applications must be manually updated to remove access\nC) Users retain access even after their account is disabled\nD) There is no formal process for access revocation',
    intent_explanation: 'ISO/IEC 27017 mandates organizations to implement Identity Federation and Single Sign-On (SSO) to enable centralized authentication across cloud services. This ensures secure access management by integrating trusted Cloud Identity Providers (IdPs) using protocols like OAuth, SAML, and OpenID Connect. Proper controls prevent unauthorized access and improve authentication efficiency.',
    criticality: 'Medium',
    maturity_levels_config: { "1": "Ad Hoc", "2": "Repeatable", "3": "Defined", "4": "Managed", "5": "Optimized" },
    related_controls: [],
    evidence_hint: 'Federated Authentication Logs: Security logs showing federated login events and user activity tracking.',
  },
];

// --- Seeding Function ---
async function seedFirestore() {
  const batch = db.batch(); // Use a batch to write multiple documents efficiently

  try {
    // 1. Seed Frameworks Collection
    console.log('Seeding frameworks...');
    for (const framework of frameworksData) {
      const docRef = db.collection('frameworks').doc(framework.id);
      batch.set(docRef, framework);
    }
    console.log('Frameworks data added to batch.');

    // 2. Seed Controls Collection
    console.log('Seeding controls for ISO 27017 Cloud Security...');
    for (const control of controlsData) {
      // Add current timestamp for created_at and updated_at
      const now = admin.firestore.Timestamp.now();
      const controlWithTimestamps = { ...control, created_at: now, updated_at: now };
      const docRef = db.collection('controls').doc(control.id);
      batch.set(docRef, controlWithTimestamps);
    }
    console.log('Controls data added to batch.');

    // Commit the batch
    await batch.commit();
    console.log('All seed data committed to Firestore successfully!');

  } catch (error) {
    console.error('Error seeding Firestore:', error);
  } finally {
    // Exit the process after seeding (important for standalone scripts)
    process.exit();
  }
}

// Execute the seeding function
seedFirestore();